export type { Department } from '@/lib/api'

// Static list kept for dropdowns that don't need live API data
export const DEPARTMENTS = [
  'ADMIN DEPARTMENT',
  'ACCOUNTING DEPARTMENT',
  'ENGINEERING DEPARTMENT',
  'HUMAN RESOURCES DEPARTMENT',
  'IT DEPARTMENT',
  'LOGISTICS DEPARTMENT',
  'MAINTENANCE DEPARTMENT',
  'MANAGEMENT DEPARTMENT',
  'MARKETING DEPARTMENT',
  'OPERATIONS DEPARTMENT',
  'PRODUCTION DEPARTMENT',
  'PURCHASING DEPARTMENT',
  'QUALITY ASSURANCE DEPARTMENT',
  'RESEARCH AND DEVELOPMENT DEPARTMENT',
  'SAFETY DEPARTMENT',
  'SALES DEPARTMENT',
  'SUPPLY CHAIN DEPARTMENT',
  'WAREHOUSE DEPARTMENT',
] as const
